spring:
  datasource:
    url: jdbc:mysql://localhost/suite_spot?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    deserialization:
      fail_on_unknown_properties: true
      fail_on_ignored_properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
